### ISSUE TITLE
Windows 10 Wallet

### ISSUE THREAD

**Issue by Humanoid1990** [Lindacoin/Linda#13] opened 2018-01-09 06:41 UTC
The Windows wallet has a virus in the file. When can we expect a new clean wallet for Windows?

**Comment by Gtibroeder** [comment] 2018-01-13 08:01
I think the project is dead?

**Comment by cksagherian** [comment] 2018-01-14 16:19
Seriously @Gtibroeder what are you talking about? The project is just coming to life? It's FARE from dead! lol

**Comment by tpenner** [comment] 2018-01-14 17:58
This is a duplicate of issue #10

**Comment by Gtibroeder** [comment] 2018-01-14 18:44
@cksagherin show me proof..

**Comment by Typhoonx53** [comment] 2018-01-31 18:45
@Gtibroeder New website with new team released today and new wallet in beta testing for starters.
DYOR and stop spreading FUD

**Comment by nisanb** [comment] 2018-02-15 18:41
Duplicate of #10 
Will be fixed at v2 -> #25

**Closed as completed** 2018-02-25 16:57 UTC
